<?php

/**********************************************************************
* R.One Creative Wordpress Theme   
* 
* File name:   
*      functions.php
* Brief:       
*      Wordpress functions
* Author:      
*      R.One Creative
* Author URI:
*      http://r1creative.net
* Contact:
*      info@r1creative.net
***********************************************************************/ 

/* ==  WARNING! DO NOT EDIT THIS FILE! (PLEASE)  ==============================
*
*	  If you know what you're doing and would like to add your own custom
*     functions to this theme, DO NOT EDIT THIS FILE. Instead, use the
*     custom-functions.php file to defin e custom functions. Adding your
*     custom functions there will make it much easier to upgrade to a newer
*	  version of this theme without losing any of your customizations.
*
* ============================================================================*/

/* ==  Start Engine ==============================*/

require_once(TEMPLATEPATH . '/engine/engine.php');

global $r1options; 

$r1options  = array(
    'superuser' => array( 'field' => 'name', 'value' => 'r1'),
    'options' => get_option('r1_options')
);

function & r1()
{
    $p = null;
    if(!isset($GLOBALS['r1val']))
    {
        $GLOBALS['r1val'] = new R1theme_controller(); 
    }
    $p = $GLOBALS['r1val'];
    return $p;      
}

r1();

function & r1ts() 
{
    $t = null;
    if(!isset($GLOBALS['r1ts']))
    {
        $GLOBALS['r1ts'] = new R1theme_support(); 
    }
    $t = $GLOBALS['r1ts'];
    return $t;      
}

r1ts();